spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ooptest?characterEncoding=UTF8
    username: ##username.required
    password: ##password.required
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    format:
      date: yyyy-MM-dd